### ISSUE TITLE
Use py.test for testing

### ISSUE THREAD

**Issue by Stranger6667** [maraujop/django-crispy-forms#463]
Hi!
I want to propose to rewrite test suite with py.test. Main goals are:
* Simplicity. Now test suite is quite complicated and has a lot of code duplication
* Granularity. py.test has beautiful feature to [mark tests](http://pytest.org/latest/parametrize.html#parametrized-test-functions) to run it in different circumstances. Running tests for different templates pack would be easy. Also py.test has [parametrization](http://pytest.org/latest/parametrize.html#parametrized-test-functions), so it should plays great with different templates packs too.
* Split setup and tests. Test code would be more clear and will have less duplication. Also test [fixtures](http://pytest.org/latest/fixture.html#fixture) will be reusable.

It will be better to show the code, so, don't you mind if I'll create some draft for that?

**Comment by carltongibson** [comment]
Hi @Stranger6667.

In general, I'm totally happy to use pytest.

My preference would be for a series of smallest-reasonable pull requests that make the migration in stages, rather than a giant pull request that moves everything in one go. 

First step then would be something like, "Install pytest. Use pietist to run existing test suite." That would be follow by "Adjusts X tests to use pytest" — and so on. 

Make sense?

**Comment by Stranger6667** [comment]
Ok, no problem, I'll update current test runner to run everything with py.test, and make PR for that.
Thanks :)

**Comment by carltongibson** [comment]
Fixed in #464
