### ISSUE TITLE
With current bootstrap4 implementation "vertical" form is impossbile.

### ISSUE THREAD

**Issue by shulcsm** [maraujop/django-crispy-forms#573]
This commit https://github.com/maraujop/django-crispy-forms/commit/a9477f115261be41a07f8aed34aa63b97db4cbb0 hardcodes classnames that from my perspective are soling edgecase.
There are multiple issues with this:

1. Broken defaults. Just enabling bootstrap4 templatepack will produce broken forms. Since for horizontal form to work classes for label and field width are expected.
2. Shoudn't "vertical" form be default? From bootstrap perspective it seems so.
3. It's impossible to produce "vertical" form at all (you have to override most of the templates)

I'd be happy to fix this, but i'm not very familar with crispy forms. I think the right way to do this would be to add class somewhere conditionally depending on form_style, like its done with form-control?

**Comment by carltongibson** [comment]
@shulcsm — feel free to give it a shot!

@zoidbergwill — Can you comment?

**Comment by zoidbergwill** [comment]
Hi @shulcsm 

I'd be happy to help you fix the problem, or fix it myself. 

I was worried about the issue when originally working on this, since I was focusing on trying to make it easier for people to migrate a project from Bootstrap 3 to 4.

I'm gonna make sure that I can reproduce what you're talking about, then I'll see if I can fix it.

1.I don't think these forms are broken by default. An inline/horizontal form has never been the default. [Bootstrap 4 docs](http://v4-alpha.getbootstrap.com/components/forms/#form-controls)

2. A "vertical" form looks like the default to me here: ![image](https://cloud.githubusercontent.com/assets/2572493/13877521/e104ff6e-ed13-11e5-802e-14c439600bfb.png), when I use [an example form](https://github.com/zoidbergwill/crispy-test-project/blob/master/bootstrap4/forms.py)

3. By a "vertical" form, do you mean the default Bootstrap form style, or an [inline form](http://v4-alpha.getbootstrap.com/components/forms/#inline-forms)?

I'm sorry, I'm battling to understand exactly what you mean and reproduce the issue.

It's possible that we just need to make a PR that drops most of the `.row` classes, like mentioned in my [previous commit](https://github.com/maraujop/django-crispy-forms/commit/a9477f115261be41a07f8aed34aa63b97db4cbb0), and then include in the docs that people will need to add the `.row` class themselves, where necessary.

If you can reproduce it in my [test project](https://github.com/zoidbergwill/crispy-test-project) and make a PR that adds a failure case, or make a gist that shows the issue, I'd happily help fix it.

**Comment by shulcsm** [comment]
Sorry for not providing an example. I got your example working, but the issue appears only if you use bootstrap with flexbox enabled. Can't seem to find official build with flexbox enabled, i guess you can use this https://cask.scotch.io/bootstrap-4.0-flex.css

**Comment by zoidbergwill** [comment]
Wow, that looks terrible.

Thanks. I will have a look at fixing it this evening.

**Comment by carltongibson** [comment]
So is this an error in the markup or in Bootstrap?

**Comment by zoidbergwill** [comment]
I think it's us, because of Flexbox and how it affects `.row`s, but I'm not actually sure.

I will try a pure Bootstrap example with the changes between Flexbox being enabled and not, tonight.

**Comment by carltongibson** [comment]
@zoidbergwill OK. Great. Thanks. 

Looking at the [example on the bootstrap docs](http://v4-alpha.getbootstrap.com/components/forms/#form-groups), the `row` class is not present.

**Comment by carltongibson** [comment]
But, of course, in the [Using the grid](http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid) section, there it is... 

It looks as if the `row` class should only be added **if** the custom widths on label and input are provided. 

@zoidbergwill Have a look. See what you think. It might be we need to refactor to support both use-cases...

**Comment by zoidbergwill** [comment]
Yeah, I added `.row`s to make migrating from Bootstrap 3 to 4 easier, but now I see it was definitely a mistake to do.

I think that's the issue.

@carltongibson That sounds like a possible solution. Will take a look.

**Comment by zoidbergwill** [comment]
I've managed to re-create it with `https://cask.scotch.io/bootstrap-4.0-flex.css`. 

Reverting that commit I mentioned fixes the default form, but breaks the horizontal form for flexbox. I'm working on a fix.

**Comment by shulcsm** [comment]
How about introduction of new form style("horizontal") here https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/helper.py#L254 and using that? That would also make possible adding default column/label width classes.

**Comment by zoidbergwill** [comment]
Here is what I've done so far with "vertical" and inline/horizontal forms:

Without flexbox:

![image](https://cloud.githubusercontent.com/assets/2572493/13913744/4300109c-ef52-11e5-8553-43385c77dfa8.png)

With flexbox:

![image](https://cloud.githubusercontent.com/assets/2572493/13913752/5460d740-ef52-11e5-9681-89d904aaa1df.png)

This way adds classes without people having to add them themselves, which is useful.

@shulcsm: That sounds like a good solution, but I think this solution I have might be simpler, if it works, since it still doesn't require users to add a `row` `wrapper_class` or anything.

**Comment by shulcsm** [comment]
Seems good, thanks.

**Comment by zoidbergwill** [comment]
The alignment of the symbols when using flexbox for the prepdended/appended fields looks weird. Is that expected?

**Comment by shulcsm** [comment]
That seems to be issue with current alpha, fixed in dev. https://github.com/twbs/bootstrap/issues/19044

**Comment by shulcsm** [comment]
Are we just waiting for merge? I disovered another issue(not related to flexbox)  that this fixes.  `.row` is adding negative margin to fields making them wider than form container.

**Comment by carltongibson** [comment]
Yeah. I'm basically happy but want to think it over one more time. 

Good news if it fixes other things!

In general I'm expecting the Bootstrap 4 templates to have some issues since they're new and have never been used in action.  Any issues you come across: open a ticket.

**Comment by zoidbergwill** [comment]
I'd love a cleaner solution, but I couldn't think of one. :P
